@api=http://localhost:8888/.netlify/functions/api

###
POST {{api}}/auth/login
Content-Type: application/json

{
    "id_token":  "eyJhbGciOiJSUzI1NiIsImtpZCI6IjIxODQ1OWJiYTE2NGJiN2I5MWMzMjhmODkxZjBiNTY1M2UzYjM4YmYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXZlbnQtZmluZGVyLTg3NWU4IiwiYXVkIjoiZXZlbnQtZmluZGVyLTg3NWU4IiwiYXV0aF90aW1lIjoxNTk1MDAwODg3LCJ1c2VyX2lkIjoidVJRcWkyWHMzVU9kaUVHajdpTjZ3bXNpTDkyMiIsInN1YiI6InVSUXFpMlhzM1VPZGlFR2o3aU42d21zaUw5MjIiLCJpYXQiOjE1OTUwOTcyMDksImV4cCI6MTU5NTEwMDgwOSwiZW1haWwiOiJlcmljQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJlcmljQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.GBXb9n_6KvLl17seH8y5l8NvNc18fi8WWdZNOLjdjJqvHeVWbx757AI9e8UFSmQKmrnfWIodJzcBqepkYwIuLVNcNSRxVtyoopYD-47W3JppVCgFc2clS4qdW2ECvQ4rtpfxOskrOEfvXzrLxIg9hUaVuCQS3UyVPBUhdRsMUs6FCHyFM5cKNrn-MY3CIhtkQrJwuA2H4uYc0NYyMszahTSVeBycp3EZLAd-J6lbcIxtSqIEb2etSdHALhm7beTbwLU53ejorJXlwJh3RE9wliygSHXrXhhefKuR1imGVPOYLEayDwa2GAUc35zX3WyuwhWzY9xUtPiT7jPK31wONQ"
}

###
POST {{api}}/auth/token
Content-Type: application/json

###
POST {{api}}/auth/logout
Content-Type: application/json